### ISSUE TITLE
Problem with private registry from code

### ISSUE THREAD

**Issue by AntonioCayulao** [sagikazarmark/helm-charts#119]
Hi @sagikazarmark 
How are you?
I have a problem with the init-container, is the same like here:
https://github.com/doitintl/kube-secrets-init/issues/22

I also need use private registries. 
Reading the code here:
https://github.com/doitintl/kube-secrets-init/blob/master/cmd/secrets-init-webhook/registry/registry.go#L103

It use a library that don't have new ways to make a login:
https://github.com/heroku/docker-registry-client/blob/master/registry/registry.go#L33
the last commit is from 2019...

Do you have any workaround about this situation or some project like alternative to make the mutation webhook?
I really appreciate any help about this.
Greetings!

**Comment by sagikazarmark** [comment]
@AntonioCayulao commented on the referenced issue: added a bit of context and offered a potential solution (although it needs coding/releasing a new version of kube-secrets-init).

Closing this one for now.
