### ISSUE TITLE
sftpgo pvc

### ISSUE THREAD

**Issue by ayushin** [sagikazarmark/helm-charts#121]
Great chart for sftpgo. But it's almost unusable without persistency of /var/lib/sftpgo - the secret key and all other configuration is lost every restart.

Would be great to have persistancy option in values (and true by default)

**Comment by ayushin** [comment]
I see that you can configure sftpgo to fetch its credentials from database, but not the host key. Would be great to have a parameter for the helm chart to simply give the host key without the need to create configmap

**Comment by sagikazarmark** [comment]
You are supposed to pass in those keys as a mounted secret/configmap or mount a volume at /var/lib/sftpgo. It's up to you, but I'd strongly suggest the first one.

The fact that database credentials can be provided through chart values is only thanks to app config being provided through there, but as a best practice, database credentials should be mounted from secrets as well. Secret values should not be fed to charts through values directly.
