### ISSUE TITLE
Add an option to disable httpd

### ISSUE THREAD

**Issue by mike-k0** [sagikazarmark/helm-charts#122]
Hi @sagikazarmark , thank you for publishing these charts!

I had a small request, if it were possible on your end. In the sftpgo chart, you currently have provided:

`sftpd.enabled`
`ftpd.enabled`
`webdavd.enabled`

Would you also be able to add `httpd.enabled` as a toggleable flag, and setting port for the httpd service to 0 if set to false for users who might wish to disable httpd? Thank you!

**Comment by sagikazarmark** [comment]
Hey @mike-k0 !

Well, disabling it is slightly more complicated, but not impossible. :)

**Comment by trippy22** [comment]
https://github.com/sagikazarmark/helm-charts/blob/81beb5347b79bb485c4c79357bbfcd637ffa093f/charts/sftpgo/templates/deployment.yaml#L59

Setting `SFTPGO_HTTPD__BINDINGS__0__PORT` to "0" will disable the httpd service altogether based on my testing. The value is currently hardcoded to "8080" and when I try to specify a different value from a values file it does not accept it currently.

**Comment by mike-k0** [comment]
https://github.com/sagikazarmark/helm-charts/blob/81beb5347b79bb485c4c79357bbfcd637ffa093f/charts/sftpgo/templates/deployment.yaml#L59

Setting `SFTPGO_HTTPD__BINDINGS__0__PORT` to "0" will disable the httpd service altogether based on my testing. The value is currently hardcoded to "8080" and when I try to specify a different value from a values file it does not accept it currently.

**Comment by sagikazarmark** [comment]
That's not enough. Ingress will also have to be disabled. Additional checks will have to be added to services.
