### ISSUE TITLE
Consider adding SFTPGo edge variants

### ISSUE THREAD

**Issue by drakkan** [sagikazarmark/helm-charts#137]
This could be useful for testing new features, and edge variants generally have the same level of stability as released versions. Thank you!

**Comment by sagikazarmark** [comment]
Where do you propose adding the edge variants?

**Comment by drakkan** [comment]
Probably in a separate chart since this is a different SFTPGo version

**Comment by sagikazarmark** [comment]
You can easily use your own image versions with the current chart. You can even override the image repository, not just the tag: https://github.com/sagikazarmark/helm-charts/blob/master/charts/sftpgo/values.yaml#L8

**Comment by drakkan** [comment]
I'm not familiar with helm charts. If the image can be easily overridden and we can set env vars for the new configuration keys then this is enough. Some users are asking for an updated helm chart to test the OIDC support I recently added

**Comment by sagikazarmark** [comment]
It's not just easy, it's a regular thing people do. The documentation (readme) of the chart should offer enough information.
