### ISSUE TITLE
Add possibility to manage log-level from the values

### ISSUE THREAD

**Issue by romankydybets** [sagikazarmark/helm-charts#151]
Add possibility to manage log-level from the values
https://github.com/sagikazarmark/helm-charts/blob/dea8535621eced1a7e6d1a0b7930412122549240/charts/kube-secrets-init/templates/deployment.yaml#L40

**Comment by Kydybets** [comment]
#160

**Comment by Kydybets** [comment]
@sagikazarmark  please review one more time

**Comment by romankydybets** [comment]
@sagikazarmark  updated docs

**Comment by romankydybets** [comment]
done
