### ISSUE TITLE
kube-secret-init 0.2.0 chart fails version check

### ISSUE THREAD

**Issue by darrylweaver** [sagikazarmark/helm-charts#30]
The new chart options in 0.2.0 include:
`kubeVersion: ">=1.16"`
On GKE the kubernetes version are strings like:
1.16.15-gke.6000
or
1.17.16-gke.1600
This does not match and hence will refuse to install on a GKE cluster.
The version string should take this into account.
This should be something like:
`kubeVersion: ">=v1.16.0-r0"`

**Comment by sagikazarmark** [comment]
Thanks for reporting. I'll fix it shortly.

**Comment by sagikazarmark** [comment]
See helm/helm#3810

**Comment by sagikazarmark** [comment]
@darrylweaver can you please try the latest version?

**Comment by darrylweaver** [comment]
I have tried the latest chart version and it is able to deploy to a GKE cluster, thanks.
