### ISSUE TITLE
Security reports

### ISSUE THREAD

**Issue by drakkan** [sagikazarmark/helm-charts#45]
Hi,

the docker image for the latest stable version of SFTPGo and therefore the helm chart could be affect by security issues, for system packages, disclosed after the image is built. 

For example, currently, the alpine image ships a vulnerable openssl version. We don't use openssl at all but this isn't the point. 

To fix this issue, I'm thinking of rebuilding the last tag on schedule, for example once a week. What do you think about? thanks

**Comment by sagikazarmark** [comment]
I don't think moving versioned tags is a good idea. Versioned artifacts should be immutable.

I think pushing new (patch) versions is the only way to publish new artifacts.

**Comment by drakkan** [comment]
Currently the 2.0.x branch has some bug fixes so I could release 2.0.3 in few weeks, we'll see in future if we have no changes and there is a security issue for a system package or for the Go version used to build the tag
